### ISSUE TITLE
email client should include url pointing to forum msg at bottom of each email, as github issues does

### ISSUE THREAD

**Issue by timotheecour** [CyberShadow/DFeed#100]
when reading github notifications (eg someone replied on an issue i'm subscribed to) in gmail, I get at the bottom of the msg something like:
```
You are receiving this because you were mentioned.
Reply to this email directly, [view it on GitHub](url ...), or [mute the thread](...).
``

could we have something similar for emails from forum.dlang.org  (cf Seb via Digitalmars-d <digitalmars-d@puremagic.com> via gmail.com )

This is quite convenient to go back to forum without having to search msg in forum.dlang.org, or to share the link with someone.

[originally posted on wrong place https://issues.dlang.org/show_bug.cgi?id=18320]

**Comment by CyberShadow** [comment]
I have, once again, no idea what you're asking.

Each email includes a link to the message being posted.

**Comment by timotheecour** [comment]
here's an example when reading https://forum.dlang.org/post/p5isu0$e0o$1@digitalmars.com via email (using gmail):

![image](https://www.dropbox.com/s/83g80ygyqqkanfw/Screenshot%202018-02-09%2001.24.19.png?dl=0)

=> contains no link to forum url (https://forum.dlang.org/post/p5isu0$e0o$1@digitalmars.com) which makes it a pain to share a particular forum message with someone

whereas github issues (seen on gmail) do show a link, eg:
![image](https://www.dropbox.com/s/ff2pskv05p85ssb/Screenshot%202018-02-09%2001.29.27.png?dl=0)

=> shows `Reply to this email directly, view it on GitHub, or mute the thread.` which links to that particular github msg https://github.com/Syniurge/Calypso/issues/75#issuecomment-358821055

**Comment by CyberShadow** [comment]
That's coming from the mailing list, not the forum.

If you want to use forum.dlang.org, then create an account and an email subscription there.
