### ISSUE TITLE
Search shows an empty second results page

### ISSUE THREAD

**Issue by wilzbach** [CyberShadow/DFeed#102]
From this results page:

https://forum.dlang.org/search?q=%23dbugfix+newthread%3Ay&search=Search

When I go to page 2: (https://forum.dlang.org/search?q=#dbugfix%20newthread:y&page=2), I get an empty page.

However, the result appears if I reorder the keywords

https://forum.dlang.org/search?q=newthread:y%20dbugfix&page=2

**Comment by CyberShadow** [comment]
Whoops, fixed in https://github.com/CyberShadow/DFeed/commit/099d81bb094a6b54c03d88f7ca1f5d75b94ac37f.

> However, the result appears if I reorder the keywords

No, that worked because it didn't have a # in it.
