### ISSUE TITLE
Enhancement: Provide a spam button

### ISSUE THREAD

**Issue by schveiguy** [CyberShadow/DFeed#104]
Just seen a bunch of spam on the NG. It would be good to have some place to report it, even if it's only via dfeed. Perhaps an email sent to admins when enough people vote it as spam?

**Comment by CyberShadow** [comment]
See here:
https://github.com/CyberShadow/DFeed/issues/84#issuecomment-350523638

**Comment by schveiguy** [comment]
Hah, almost exactly what I was asking for 😉 I guess I should have looked first.
