### ISSUE TITLE
Design improvements from forum post

### ISSUE THREAD

**Issue by andre2007** [CyberShadow/DFeed#108]
Please see improvements proposed here
https://forum.dlang.org/post/sxsiedhvuaqvgwrwvmlb@forum.dlang.org

**Comment by CyberShadow** [comment]
I fixed the redundancy in the group captions.

A redesign would need a much more extensive discussion. Several people worked on the current design, and I think you will find that there will be users opposed to changing it. The same goes for removal of columns, considering that there are issues / pull requests in this repository pertaining to adding additional functionality to them.
