### ISSUE TITLE
Display IP

### ISSUE THREAD

**Issue by p0nce** [CyberShadow/DFeed#109]
Sockpuppets account are becoming quite visible, and IP would bring additional annoyment for the troll.

Example: watcher, silentwatcher, Rose, Tourist looks like only one troll in https://forum.dlang.org/thread/ylwktmssgntvoddubnwl@forum.dlang.org

**Comment by CyberShadow** [comment]
That person is using a lot of IPs, mostly IPv6, so I don't think it will accomplish anything in this case.

**Comment by p0nce** [comment]
Sad.
