### ISSUE TITLE
Segmentation Fault Message with Dmd

### ISSUE THREAD

**Issue by Unlimiter** [CyberShadow/DFeed#111]
**OS**: Ubuntu 18.04
**architecture**: i386

---
I have installed dmd (dmd_2.086.0-0_i386.deb) from https://dlang.org/download.html.
When I compile any '.d' file with dmd, no matter what it contains (even an empty file with an empty main function), and run the output file, it says "**Segmentation fault (core dumped)**".
Things work fine with gdc, however I don't like passing every imported file to it. With dmd, I just pass "-i", and it knows what file to link.

What do I do to make dmd produce good binaries.

**Comment by CyberShadow** [comment]
This is the issue tracker for the forum software running on forum.dlang.org.

To ask a question about using D, go here: https://forum.dlang.org/group/learn
To file a bug report against the compiler, go here: https://issues.dlang.org/enter_bug.cgi
