### ISSUE TITLE
Request: provide Docker image 

### ISSUE THREAD

**Issue by Spass1966** [CyberShadow/DFeed#112]
This may not be something the developer is interested in doing, if so, please feel free to close.

I've been looking at lightweight mailing list solutions that also provide an NNTP feed and forum but Synology users are stuck only using Docker images if no binary is built specifically targeting its flavor of Linux, DSM.

An image kept in sync with the project would be a boon to users looking for a one-click solution.

**Comment by CyberShadow** [comment]
After building, the binary has very few external dependencies (D stdlib/runtime and SQLite), so wrapping it into a container is trivial. However, as DFeed only provides a web frontend, you will probably want to include other components as well (Mailman or an NNTP server). Which components those are depends on your goal.
