### ISSUE TITLE
[enh] Warn users not to resurrect old threads without good reason

### ISSUE THREAD

**Issue by ntrel** [CyberShadow/DFeed#113]
Resurrecting old threads e.g. just because people want to see if anything has happened since is very annoying as it makes for lots of scrolling (e.g. on a phone) with the threaded forum view. This happens quite regularly on the general forum (after people find an old message e.g. through Google). DFeed could:

1. Inform a user when replying to threads older than 3 months, that this is discouraged. Suggest they make a new thread and link to the old thread (even provide a button to do this for them). Make them confirm that they want to resurrect the thread.

2. Don't display messages older than 3 months on each forum's main page for the threaded view, just show a link with three dots going to the first message page for the thread with the full thread history expanded.

**Comment by CyberShadow** [comment]
>     1. Inform a user when replying to threads older than 3 months, that this is discouraged.

There is something like this already:

https://github.com/CyberShadow/DFeed/blob/8dd9b893d8bf10ca70d4c07d225bdf3c46d3564f/src/dfeed/web/web/posting.d#L109-L111

Though, the current message merely warns without suggesting something.

We could add an additional lint check upon posting.

> is very annoying as it makes for lots of scrolling (e.g. on a phone) with the threaded forum view.

I think this is the real problem. Being able to fold (parts of) a thread has been suggested, but I haven't found a way to approach / implement this functionality in a sensible way so far.

**Comment by ntrel** [comment]
Great, thanks.
