### ISSUE TITLE
Is poster IP and user agent published intentionally?

### ISSUE THREAD

**Issue by anon17** [CyberShadow/DFeed#114]
It's not like there's anyone who doesn't know them, but they aren't published routinely either, are they?

**Comment by CyberShadow** [comment]
I believe the headers are standard-ish.

The IP and user agent is also published when posting via NNTP (and, sometimes, by email), so from that perspective it's not unusual.

**Comment by anon17** [comment]
I mean when published from dfeed.

**Comment by anon17** [comment]
When posted from dfeed.

**Comment by CyberShadow** [comment]
Yes.
