### ISSUE TITLE
Delete account

### ISSUE THREAD

**Issue by minas1** [CyberShadow/DFeed#115]
I'd like the option to delete my account.

If not possible, can I just tell you my username to delete it?

**Comment by CyberShadow** [comment]
Sure...

**Comment by minas1** [comment]
Thanks. The username is _minas1_.

**Comment by CyberShadow** [comment]
There is now a section on the settings page to perform some account actions, including deleting the account.

Here is the link to the account deletion form:
https://forum.dlang.org/delete-account

**Comment by minas1** [comment]
Awesome, thanks!
