### ISSUE TITLE
Posting doesn't go through; "Posting status" page keeps refreshing

### ISSUE THREAD

**Issue by wolframw** [CyberShadow/DFeed#117]
I tried posting to the D forums today. Upon sending the post, the "Posting status" page appeared saying "Message sent" and refreshing over and over again (see below). The post however did not (yet?) appear in the D forums. The post ID is rvoemoamtzkxzgzawkrj.
![posting status](https://user-images.githubusercontent.com/5099115/81313054-e32ae000-9076-11ea-8863-2fb66b8455d5.png)

**Comment by CyberShadow** [comment]
I don't see a problem on the forum side. Please resubmit the post. (Let me know if you'd like a copy of your post.)

**Comment by CyberShadow** [comment]
Oop, here it is:
https://forum.dlang.org/post/rvoemoamtzkxzgzawkrj@forum.dlang.org

It appeared on a full redownload.
