### ISSUE TITLE
Markdown tables spuriously fail

### ISSUE THREAD

**Issue by dkorpel** [CyberShadow/DFeed#127]
Reduced to:
```
| A                                | B                            | C  |
|----------------------------------|-------------------------------|----|
| A                                | B                             | C  |
| A                                | B                             | C  |
```

Which should render as:

| A                                | B                            | C  |
|----------------------------------|-------------------------------|----|
| A                                | B                             | C  |
| A                                | B                             | C  |

But on the forum preview it shows:

![image](https://user-images.githubusercontent.com/14114684/122386252-00b2c480-cf6e-11eb-9507-5b182647ea19.png)

And if you align the last column:
```
| A                                | B                             | C  |
|----------------------------------|-------------------------------|----|
| A                                | B                             | C  |
| A                                | B                             | C  |
```

It fails completely and shows this:

| A | B
| C |
|----------------------------------|-------------------------------|----|
| A | B
| C |
| A | B
| C |

If you tighten it up:
```
| A | B | C |
|---|---|---|
| A | B | C |
| A | B | C |
```
It works correctly. I have no idea what's happening.

**Comment by CyberShadow** [comment]
Argh. It's a bad interaction with [RFC 2822 wrapping](https://datatracker.ietf.org/doc/html/rfc2822#section-2.1.1).

Standard Markdown fits and works well with hard-wrapped text, however, that does not extend to GitHub's extensions.

So, we need to heuristically detect and exempt lines containing Markdown tables from wrapping.

**Comment by dkorpel** [comment]
So it's simply word wrapping around 74 characters before converting to markdown? At least I can work around that for now by making my table smaller.

**Comment by CyberShadow** [comment]
Should be fixed now.

https://github.com/CyberShadow/ae/commit/5982fbdf6859f2ec6f0b13e114cb1e03c4cf6b24

**Comment by dkorpel** [comment]
Thanks for your swift action!
