### ISSUE TITLE
identify really old messages you are replying to

### ISSUE THREAD

**Issue by schveiguy** [CyberShadow/DFeed#128]
Obviously this can't be enforced via the NNTP interface, but I'm thinking there should be a hoop you have to jump through when you reply to a message more than a certain age (like 2+ years maybe?). I think most of the time, people mistake the thread as current, because they reached it on the web site via a search.

Like maybe:

```
Warning! The message you are replying to is 1522 days old.
Resurrecting old threads can be disruptive to the forums, as
this will bring the thread to the top of the fourm, and people
will mistake old messages as new. If you wish to proceed,
please type `1522 days` in the box below
```

e.g.: https://forum.dlang.org/post/pnpwlixcccweeehjanip@forum.dlang.org

**Comment by schveiguy** [comment]
Also might not hurt to stylize old messages in a way that shows their age, like maybe the date gets colored differently

**Comment by CyberShadow** [comment]
It's already there:
https://github.com/cybershadow/DFeed/commit/6c57322fee53c9a340c269926a333634a8a9457b

And another warning here:
https://github.com/cybershadow/DFeed/blob/master/src/dfeed/web/web/posting.d#L122-L124

If people are posting regardless of this, then they're 1) ignoring the banner at the top 2) hitting the "Ignore" button after submitting their post.

Not much we can do about this at this point.

**Comment by schveiguy** [comment]
2 weeks is not a long time though. I'm talking about ancient threads that have no relevance today. 

Hitting an "ignore" button is trivial, having to type out that they understand the age of the post would be less easy to mindlessly do.

But I wouldn't add that requirement for 2 week old posts, just something that's really old (at least a year).

**Comment by schveiguy** [comment]
Hm... I didn't see the 7 week rule that you linked to, I'll have to see what that does.

**Comment by schveiguy** [comment]
OK, I see the ignore button, yeah, I find it hard to believe that someone clicked through that mindlessly.

**Comment by schveiguy** [comment]
An alternative might be to prevent replying to a message older than one year. Just change what the reply button does to what the lint rule requires (creating a new post and linking to the old one).

**Comment by CyberShadow** [comment]
I think that won't stop people from replying to outdated information thinking that it is still relevant today. Creating a new thread is also noisier than replying to an old thread.

**Comment by schveiguy** [comment]
> Creating a new thread is also noisier than replying to an old thread.

I disagree. With an old thread link, you have to click through to see the old thread, it doesn't appear as recent. What happens now (especially for NNTP users and people who are using threaded view) is that you see all of a sudden this whole thread show up at the top.

What ends up happening is that people then reread the old thread thinking it's new, and start replying to other old posts in the thread (not the new post).

But I'll leave this closed. Just a suggestion.

**Comment by CyberShadow** [comment]
Hmm. Yeah, I guess it depends on how you interact with the newsgroup. In horizontal-split view, old threads are fairly obvious. Vertical-split view doesn't do threading at all.
