### ISSUE TITLE
Split view panes overlap on chromium

### ISSUE THREAD

**Issue by John-Colvin** [CyberShadow/DFeed#13]
This could be a problem on other browsers as well, but I haven't tested it.

Occasionally, seemingly unpredictably, the element id:"group-index" is approximately 30 or 80 pixels too wide on the right hand side, causing it to overlap with the message window.

**Comment by John-Colvin** [comment]
I'm still seeing this on OS X with safari, chrome and firefox. https://www.dropbox.com/s/53id81u1rknpyse/Screenshot%202015-05-29%2016.07.11.png?dl=0

**Comment by John-Colvin** [comment]
It seems to be related to slow internet connections

**Comment by John-Colvin** [comment]
group-index is overflowing group-split-list

**Comment by CyberShadow** [comment]
> group-index is overflowing group-split-list

That might be fixed in the `next` branch, it uses a different approach to overflows.
