### ISSUE TITLE
corrupted gravatar link

### ISSUE THREAD

**Issue by anon17** [CyberShadow/DFeed#133]
The href attribute on the link is partially merged with the title attribute.

**Comment by CyberShadow** [comment]
CC @WebFreak001

**Comment by anon17** [comment]
The code is in part/post.d
```d
putGravatar(gravatarHash, "http://www.gravatar.com/" ~ gravatarHash, `title="` ~ encodeHtmlEntities(_!`%s's Gravatar profile"`.format(author)), 80);
```

**Comment by WebFreak001** [comment]
@CyberShadow is my PR deployed yet? I thought that part should have been fixed by my PR

**Comment by CyberShadow** [comment]
Oh, did I not deploy it? My bad

**Comment by CyberShadow** [comment]
Seems to be fixed now, thanks!
