### ISSUE TITLE
Wrong quote nesting as a result of slightly broken markdown syntax

### ISSUE THREAD

**Issue by FeepingCreature** [CyberShadow/DFeed#138]
Consider my post at https://forum.dlang.org/post/zclzqueiosglcnkkbbbj@forum.dlang.org : my comment shows up one quote level deep. Luckily I still had the previous page in buffer, so I know that this is what I wrote:

https://i.imgur.com/YjOIyIH.png

Note how the two-deep quote is slightly misquoted. This seems to throw off the Markdown quote handling for the rest of the post.

**Comment by CyberShadow** [comment]
That is weird.

It might be an issue with the unwrapping we do before we hand the text off to the markdown renderer. But if it's not that, then it would be a bug in the renderer ([cmark-gfm](https://github.com/github/cmark-gfm)).

**Comment by CyberShadow** [comment]
OK, it's definitely a bug in cmark, lol.

https://forum.dlang.org/split-post/zclzqueiosglcnkkbbbj@forum.dlang.org

It's generating a `</blockquote>` without there being any opening block quote.

**Comment by CyberShadow** [comment]
Got it. Our preprocessing missed a corner case.
