### ISSUE TITLE
RSS: Latest threads on Announce is empty.

### ISSUE THREAD

**Issue by kassane** [CyberShadow/DFeed#157]
https://forum.dlang.org/feed/threads/announce

> Feed Latest threads on Announce is empty. I'll notify you when I'll get something.

But, https://forum.dlang.org/feed/posts/announce has content.

**Comment by CyberShadow** [comment]
Feeds include items from the last 24 hours by default.

See e.g. https://forum.dlang.org/feed/threads/announce?hours=168
