### ISSUE TITLE
Password/username for my account

### ISSUE THREAD

**Issue by dukester** [CyberShadow/DFeed#161]
Need to talk to Dlang forum webmaster/moderator.
Got issues with forum login.
Who's the Forum honcho?
BTW, IMO there should be a link somewhere on the forum to communicate with the Forum honcho!
--
Duke

**Comment by CyberShadow** [comment]
> Got issues with forum login.

Please create a new account. This will not prevent you from using the same name or email address when posting.

> BTW, IMO there should be a link somewhere on the forum to communicate with the Forum honcho!

Sorry, I don't have the resources to provide support.

There is a help page here:
https://forum.dlang.org/help

You can find the D language foundation's contact information here:
https://dlang.org/foundation/about.html
