### ISSUE TITLE
Feature Request: periodic digests via email (and/or IRC?)

### ISSUE THREAD

**Issue by Infiltrator** [CyberShadow/DFeed#17]
DFeed is great; scrolling up through the IRC channel to look through it all is not so.

Basically, the idea is to get DFeed to send periodic digests via email (and/or maybe IRC?).

So, users would need some way to subscribe (possible by talking to DFeed in #d) and specify a period (these can be pre-defined or customisable with a maximum).  DFeed would then store a list of subscribers and their periods; and it would also store all of its events up to its maximum period.

I would suggest customisable per-user periods, with a resolution of 1 hour, and a maximum of 168 (1 week).

**Comment by CyberShadow** [comment]
Why not subscribe to the mailing list, and configure it to send digest emails?

**Comment by CyberShadow** [comment]
Let me know if you still need this.
