### ISSUE TITLE
Reply preview

### ISSUE THREAD

**Issue by Wyatts** [CyberShadow/DFeed#24]
Because of the automatic wrapping, it's sometimes hard to know what your post will look like once you send it, especially when you're dealing with quoting and its associated format mangling.  A preview that allows users to load what it will look like after posting would be helpful to alleviate this.

**Comment by CyberShadow** [comment]
DFeed now has a "Save and preview" button, in addition to the improvements described in #26.

http://beta.forum.dlang.org/
