### ISSUE TITLE
Enable lookup by date

### ISSUE THREAD

**Issue by schveiguy** [CyberShadow/DFeed#3]
I generally use a newsreader program to view newsgroups.  However, occasionally I want to refer to an older post.  Using dfeed is great to be able to provide a link to said post, however, there is no search by date.  If I know the date of the post I want to find, I should be able to specify that date and have a list of messages posted on that date appear.

**Comment by CyberShadow** [comment]
Search by date is now implemented.

http://beta.forum.dlang.org/

> Speaking of which, it would help if forum.dlang had better URLs

https://issues.dlang.org/show_bug.cgi?id=14045#c13

I think URLs in dates are ill suited for forums, where the date range of posts in a thread can span months or years.
