### ISSUE TITLE
Ignore github commit messages (or any other filters we want)

### ISSUE THREAD

**Issue by schveiguy** [CyberShadow/DFeed#34]
At the moment, the phobos/druntime/dmd internals mailing list forum interface is nothing more than a mirror of github commits.

See here my post about it: http://forum.dlang.org/post/op.xckojzu3eav7ka@stevens-macbook-pro.local

I also, in a recent reply to that, posted a filter I established for my mail client that will ignore certain ML messages that are always github commits (http://forum.dlang.org/post/op.xc8a3cdzeav7ka@stevens-macbook-pro.local). Could dfeed allow filtering of mail to ignore those messages? They are mostly noise.

**Comment by CyberShadow** [comment]
I don't think I'm going to do this. Not only is this difficult (e.g. you can't efficiently do pagination when you're filtering items), but it fixes the problem only on one end (the forum), while allowing it to persist for mailing list users (and NNTP users for NNTP groups).

> Well, you can't post to the mailing list from the web interface anyway

Now you can, FWIW.
