### ISSUE TITLE
Unaligned scrollbar on dlang.org widgets

### ISSUE THREAD

**Issue by BBasile** [CyberShadow/DFeed#43]
It looks like this [css property](https://github.com/CyberShadow/DFeed/blob/master/web/static/css/dfeed.css#L1183)

leads to a display problem under Opera 30 - Windows:

with the property (current version):

![with](https://cloud.githubusercontent.com/assets/7805501/8685156/2ba86592-2a7d-11e5-8df9-8c96c9f8fc3c.png)

without the property:

![without](https://cloud.githubusercontent.com/assets/7805501/8685158/2ee56fac-2a7d-11e5-8bb8-3934384da178.png)

**Comment by CyberShadow** [comment]
It is a known problem if your font size is set to a non-default value.

Can you propose a solution that works in all browsers?

**Comment by BBasile** [comment]
No. I just wanted to report.
