### ISSUE TITLE
Incorrect RFC 1522/2047 encoding of quoted text

### ISSUE THREAD

**Issue by schuetzm** [CyberShadow/DFeed#44]
Example:
http://forum.dlang.org/post/movlj4$29cb$1@digitalmars.com

**Comment by CyberShadow** [comment]
I don't understand, what is the desired action / change in DFeed here? The Unicode characters are correctly encoded and decoded in DFeed as far as I can tell.

**Comment by CyberShadow** [comment]
If you mean that you see `=?UTF-8?B?R3LDuHN0YWQi?=` in Walter's message, that's because Walter's UA doesn't understand Unicode encoding of headers.

This encoding style is used ONLY in headers. If it is encountered in the message body, it is treated like any other sequence of characters.

**Comment by CyberShadow** [comment]
BTW I see no relation to the message's subject here. The subject of the message you linked is "Re: Rant after trying Rust a bit".

**Comment by schuetzm** [comment]
Sorry, I thought it was somehow caused by DFeed inserting the original sender into the reply without unescaping it. But you're right, Walter's using a different user agent which seems to have problems. Or, as someone else has since pointed out, Ola's newsreader wrongly uses quotes _and_ encoded atoms at the same time. Sorry for the noise.

**Comment by d-random-contributor** [comment]
The original message was sent from DFeed, so headers come from DFeed? The original diagnosis was that the escaped name is incorrectly quoted, which causes Thunderbird to choke on it.

**Comment by CyberShadow** [comment]
I am away from D stuff so  haven't read the entire thread. Can you propose a pull request? The relevant code is in ae.net.ietf.message, `encodeRfc1522` function.

**Comment by d-random-contributor** [comment]
As I understand, it's called like this:
encodeRfc1522("\"Ola Fosheim Grøstad\" <ola.fosheim.grostad+dlang@gmail.com>")
Should be called like this:
encodeRfc1522("Ola Fosheim Grøstad <ola.fosheim.grostad+dlang@gmail.com>")

**Comment by d-random-contributor** [comment]
```
- headers["From"] = format(`"%s" <%s>`, author, authorEmail);
+ headers["From"] = format(`%s <%s>`, author, authorEmail);
```
Something like this.

**Comment by CyberShadow** [comment]
Let's try it:

https://github.com/CyberShadow/ae/tree/17bf03e6121a3338c4310ee5ad9728d60b25947d

Hopefully this will not cause issues.
