### ISSUE TITLE
Development\Druntime topic is not updated

### ISSUE THREAD

**Issue by data-man** [CyberShadow/DFeed#46]
Frozen on June 14.

**Comment by CyberShadow** [comment]
Fixed, thanks

**Comment by data-man** [comment]
And again, the same problem.

**Comment by CyberShadow** [comment]
Looks fine to me:

http://forum.dlang.org/group/druntime

What is the problem?

**Comment by data-man** [comment]
And commit with Windows headers is showed?

**Comment by CyberShadow** [comment]
Well, it hasn't been sent out, and it's not here:

http://lists.puremagic.com/pipermail/d-runtime/2015-October/thread.html

which means that the problem is either with Brad's mailing lists or GitHub.

**Comment by data-man** [comment]
Ok, sorry.
