### ISSUE TITLE
The last paragraph is sometime stripped

### ISSUE THREAD

**Issue by Blumerline** [CyberShadow/DFeed#48]
This happens to me some time to time when using the forum web interface but now I have a good example:

If you look at [this Bugzilla comment](https://issues.dlang.org/show_bug.cgi?id=15335#c1) and [how it's displayed in the web interface](http://forum.dlang.org/post/mailman.2229.1447695815.22025.digitalmars-d-bugs@puremagic.com) you'll see that the last paragraph is missing.

**Comment by CyberShadow** [comment]
This is how the message was received by DFeed:

http://forum.dlang.org/source/mailman.2229.1447695815.22025.digitalmars-d-bugs@puremagic.com

As such, the problem lies with the NNTP server, Mailman server, Bugzilla, or something in-between.

Please file an issue in Bugzilla and CC Brad Roberts.
