### ISSUE TITLE
Error: module ssl is in file 'deimos/openssl/ssl.d' which cannot be read

### ISSUE THREAD

**Issue by PaulCapestany** [CyberShadow/DFeed#49]
Hi there,

This project looked cool to me, but this is my first time ever using D (so apologies if this is a trivial issue) and when I try to run `rdmd dfeed` I get the following error:

```
ae/net/ssl/openssl.d(28): Error: module ssl is in file 'deimos/openssl/ssl.d' which cannot be read
import path[0] = .
import path[1] = /Library/D/dmd/src/phobos
import path[2] = /Library/D/dmd/src/druntime/import
Failed: ["dmd", "-v", "-o-", "dfeed.d", "-I."]
```

Any suggestions on how to address this would be hugely appreciated..

**Comment by CyberShadow** [comment]
Just grab https://github.com/D-Programming-Deimos/openssl and add it to your D search path. Copying or symlinking the deimos directory to DFeed's should do the trick.

**Comment by PaulCapestany** [comment]
Thanks, that got things further along :)
