### ISSUE TITLE
Links has smaller font size than the text

### ISSUE THREAD

**Issue by jacob-carlborg** [CyberShadow/DFeed#52]
I'm not sure if this is a bug in iPhone 6 or something with DFeed, but I've only seen it on the forums. When I view the site in landscape mode, for some links, in the text of a post, the links have a smaller font size. The computed font size is 12px. When I click on the link nothing happens and the font size gets larger (standard size, 20px). Clicking on the link again navigates to the linked site.
![screen shot 2016-01-16 at 14 26 41](https://cloud.githubusercontent.com/assets/306980/12372578/e9a260e4-bc5d-11e5-82d9-3799c83c2a59.png)
![screen shot 2016-01-16 at 14 27 05](https://cloud.githubusercontent.com/assets/306980/12372579/ebd8bc8c-bc5d-11e5-9f47-4dd1bec9bd35.png)

**Comment by CyberShadow** [comment]
There is definitely nothing in the code to shrink or enlarge links. It might be an iOS Safari feature that's manifesting in an odd way.

I don't own an iPhone, any way for me to reproduce this issue on a Windows or Linux PC?

**Comment by CyberShadow** [comment]
Maybe `-webkit-text-size-adjust` would fix it... but I have no way of testing.

**Comment by jacob-carlborg** [comment]
> I don't own an iPhone, any way for me to reproduce this issue on a Windows or Linux PC?

I have only seen this problem in the simulator and on an actual iPhone.

**Comment by jacob-carlborg** [comment]
It looks like `-webkit-text-size-adjust: 100%;` forces the link to not change the font size. But then it will be consistently smaller. Putting the same rule on the rest of the content and increasing the overall font size would fix that problem.

**Comment by jacob-carlborg** [comment]
The computed font size of the text is 12px on iPhone 6 in portrait mode and 20px in landscape mode.

**Comment by jacob-carlborg** [comment]
For the line height it's 13px on portrait mode and 21px in landscape mode.

**Comment by CyberShadow** [comment]
> I have only seen this problem in the simulator and on an actual iPhone.

I got the iOS simulator running in a VM but couldn't reproduce the issue:

![](http://dump.thecybershadow.net/1cf0de49858f4d35748903db410ca961/000001B8.png)

**Comment by jacob-carlborg** [comment]
It only occurs in landscape mode. There's a menu item to rotate the device in the Hardware menu.

**Comment by CyberShadow** [comment]
Ah OK, reproduced.

For some reason, the (simulated) iPhone 6 thinks it can fit MORE text on its 4.7" screen than my 5.7" Note 4.

I wish CSS units such as `mm` still meant something today.

**Comment by CyberShadow** [comment]
I disabled text-size-adjust and removed font size scaling. How does http://beta.forum.dlang.org/ look/feel for you now?

**Comment by jacob-carlborg** [comment]
That looks better. Now I think I can comfortably read in portrait mode :smiley:. But I noticed the top menu header doesn't stretch all the way to the right side. BTW the rest of the page doesn't stretch all the way either.
![screen shot 2016-01-17 at 14 14 48](https://cloud.githubusercontent.com/assets/306980/12377649/0e90702c-bd25-11e5-8318-f7fd205e1233.png)

**Comment by CyberShadow** [comment]
Took me a while to figure out. Looks like Safari doesn't take word-spacing into account of width calculation for floats.

```diff
diff --git a/css/style.css b/css/style.css
index 5dc278f..727d585 100644
--- a/css/style.css
+++ b/css/style.css
@@ -522,13 +522,12 @@ body.std .subnav a.package
 {
     padding: 0.3em 0 0.6em 0;
     text-align: right;
-    word-spacing: 0.5em;
 }

 #content #tools .tip
 {
     display: inline-block;
-    word-spacing: 0;
+    padding-left: 0.5em;
 }

 .expand-container > .expand-toggle::after
```

ping @aG0aep6G

**Comment by CyberShadow** [comment]
I understand this is now resolved.
