### ISSUE TITLE
Small margin when replies column is not shown

### ISSUE THREAD

**Issue by jacob-carlborg** [CyberShadow/DFeed#54]
I think the margin on the right side of "20 minutes ago" is too small. It's not really visible on the screenshot below or in the simulator because it's so big. But on the phone it doesn't feel right and it feels like it's smaller than it was before, when the "Replies" column was present. It also feels like there's a bigger margin on the left side of the avatars/images.

![screen shot 2016-01-21 at 20 43 01](https://cloud.githubusercontent.com/assets/306980/12492331/fa250306-c07f-11e5-9484-c222c1b5c698.png)

I think the margin for the on the right side of "2 days ago" would look better.

![screen shot 2016-01-21 at 20 43 46](https://cloud.githubusercontent.com/assets/306980/12492336/fd95f7ca-c07f-11e5-946a-e1c57dda27cf.png)

A general guideline would probably be, in the simulator, if the scrollbar covers something, then it's too close to the edge.

**Comment by CyberShadow** [comment]
I guess this is fixed now.
