### ISSUE TITLE
Locked outside the forum because of cookie size

### ISSUE THREAD

**Issue by cym13** [CyberShadow/DFeed#55]
I just got locked outside the forum because it made its cookie so bit it couldn't handle it anymore (err400, Header or Cookie too big). Isn't it supposed to remove old events to make room for the new ones? I know I browse the forum a lot, but it still came to me as a surprise.

**Comment by CyberShadow** [comment]
Can you post a screenshot of the error?

**Comment by CyberShadow** [comment]
Does it happen now?

**Comment by cym13** [comment]
I'm sorry, I don't have any screenshot to show because I deleted the cookie (which unsurprisingly solved the issue on my side). It was the standard "Error 400" page though, white with the server version, a bit like this one http://i.stack.imgur.com/JX31h.png but making mention of the cookie size in the reason.

**Comment by CyberShadow** [comment]
Okay, well, I searched online for the error message and got results regarding nginx, so I increased the nginx instance's maximum header size. This should be fixed now.

**Comment by cym13** [comment]
I had the same problem as before so this time I kept the cookie:

![2016-05-16-162550_1366x768_scrot](https://cloud.githubusercontent.com/assets/4958985/15295645/c712355c-1b91-11e6-9716-088acfc40935.png)

Cookie:

dfeed_readposts=eAHtXQ94VMW1P3P3ZrnZhngTIgSIMAkBAqZ2QahRESZxoYsgrny0D7W+LtT2If2qoZ+taKlOQsRga10oVqqtLupT+te0r3/0e7Zelae0n+0XaluL9ZWAtlJeq9TSQqWYd2buvbt3N7vJZvPHDZkDmT9nzpw585s/d+7M3XsBFCkEFALDjMCUTcNcoCpOIaAQUAiMQgT4lZ8nhVZtgxaDKY0yCs00ZY9CQCEAMGPyORKGyJpt9khVoCgEhgsB3WQA1tThKm4IymlwdVI3ABroiTAk2UlewYX8FUWAFfGYXXAmjkiDwtJqDrgGYqB1FNzybESCqoxWCCgEFAIKAYXAu4pAJWwGNqfHRb356Li+zcJbLTMgxZhwK2VQOSMAgciaarQS224o75Y5mLoB26ZBDTEqjpKIDnL/TMd7i4KnocSl4CuvDFQIKAT6QoDpAXtC60twyNM1JosgpMdlfMiLVgUoBEYAAvxNXxYrY4/UZ0gZASuUDFYrlkJAIaAQUAjkjADv7h6Ts7ASzIQAewdimfg58xi8dsheuVqklOWcTQkqBBQCCgGFgEJAIaAQUAiMGgRY3K7qUD3rxafS5INkuBeUfO77b0V5gpxUkaeCwcnGfnLPHPVzpsHBUmlRCCgEFAIKAYWAQkAhoBBQCOSAwIm/5iCkRBQCCgGFgEJAIXB6IsDfGM0H77GqP9Rhu/Je2rYT+MUURdSzaL2ApJIUAgoBhYBCQCEw6hGgUI7P0eGhKE85GMXfsrUMHzZrT36mfWa8gkdNXLrgCyMIhIavcFWSQkAhcLogEBUVodBqlafMZ6dL9VQ9Ch8BxtBGdQEr/IZSFvaJAGe0BLaLH0LqOKt6iHMA9u9NkmPiXLvSKBVhityUN0S0Cq6iYUKgdsIwFTT0xZDw0JdxGpZwtFg7DWulqqQQUAgoBBQCCgGFgEJAIaAQUAgoBBQCCgGFgEJgNCGQ3N/xE0+9o96Ih6+CCgGFgEJAIaAQGH0IlEBz9YBqzULPDij/KXksOiAVIzDzJvxIQI/1yFNlI6Im8Wyv/R0R1isjFQIKAYVAvxAY0R+i7FdN8xK2hvlXhyce+OT8vAxVmRQCCgGFgEJAITCqEOi45CENzNQPsK2O+NbnDQKTObmb3466MeUrBBQCCgGFgEJAIaAQUAgoBBQCCgGFwGmNwDX2x+opVOb7QYc+4Qn/Pfk9Xvc5rx7nqH1q6UVgUJX1Uk6BJ1EIzyqWWDDX0tTNA5er/CFCoJdvm3BRJL7CkK4KWLou2oUKDj5SQPHPiUiOchQCCoGhRmB1sgBeLMJsuuRwoN537MjpNClaqCHdtTMqLrC9TEOYqouHmEyGc1EehKo15uTUmE4DYvIaOqJYHLTdhvOjt1F6lJeoigtDDwnFUAicPgiwLSFjk+j0w/0Qx5BBuHHRkKkeDMVhBNuZWxjq41KnzVgswxlmwZibQwr07WRQ0XemDBJRoSgxI2YQGAoWnT6tte/Jt3ooih5knf5s+ni2hMHiEyNzF8iKa9aEwbJI6Rl2BNzF1bAX/K4UaJ5SfVgCzx34GWjy+Q7uXGPcVmFuYAT4J/7R/eh9ql09LVXuCcsgTWdkjSscs0KTKcG+l8eUJpZIZqNrTk3UWwUUAoWFAL4JHzdyioCBGRiQZVaNyK7zmQPSojIrBBQCQ44AiwYX9LEfodF0K7Jv+EYrDCCmvR8ss+EBmke9s1HMcXpox29uKCpQBOafGT49WqdF9jjCHmlqmAVE50Sn9+0KrQVYCXyiCYwBMHOLp4dig9DhbBRnRNhFyrMhPpzFq7LyQIBrfig2gFsArXlkH6os7Kcjf8weFl+BosCoSQxSgUiljA83JurJ8Cg1ddzmgOugAmRAHXD81+NMl+ESOppy3Uszza6UdHlTvyuRpkxFFQLvCgKi42Y5FcnRHkb2ysc7gIYZXvtwdHI5sOVzC0FUQhk6WQ99ME1R/ggMZDLUTJmbYRPJRYtrhcF73i24aXn7bD5PzxtOZwxiL8FlYQ/tWM/qzxEwnJ0RQ3dqbc/kGcRdlq+PB34cOdqnIleh8vtCAO9AJZqpkBoySvvKnJ5e8V87Qum8AozrlXIZUULn2cbRXe9tESGqAQGLoJNGyKignpWLlYqWLY0CkiK1TsD1eqgTCZkPyN0sI93X7A7UVzXwVV4mw/tK2Rx9Cav0fBCg+tjes2Hv5NQRydhTe88+ylLbFUSF1OJm2YMkPtAm8c4+FGsn/nqleBmFZny78+rFuDF2XuSs+f5rYJL4LLKgMohSMbvblwixLkfyFmFzPK5nTcg97N6D1L4X6EXIuUaxpAhNBlVo4AhIgEukHp6irSkl5on0o6d2kg4NaKpejyYVLEwE3GUd3v3s2IYRljCTJkJDGtDtDYCsE44wsAJmo2ubGgUull9i91BS1oyuQCH7e2qEdc7EZxtKIjkbXH1iJvdF7Xt100hCkn5TSnPSyAb8nlrrp3PdquDDQCxzqZoOlJipdc4sOeK4OIYq7cWr/cveHK7MKXXk0A7Acc61UtjZIrRlfLakgfCJfYWwVXAWsvtXPzT246LRD61KNBMCOJq8zQU8XoVbdF/ua3id2pxJWZLH8fBDkBjO7pAWcS0lJjgDJqk+ly7DIUxrnNle/y6QFa3zlmnGl4PQaTRJK0oIx0UtipWImSyOlwv7iiFsdkCy65IsLcAdhdmrEWMZ0mhY49EknyeDWUIJCcckW4yJmdqLb5bcQ85OXE29JXGz3WwsCPO8Vg1JOKVV8irBSs1FU6P5xPzMzcVaxa0adaMmjHODrk/BQAmf6Njc5olg75Re54grnp6A/B59tM9h4yrrr8/QcGl7S8wp1nO32V9lp5d8VDYMy7NSzB7jGRo3T4UDymZ3T/FRh7Su9YeofDBgQMr7l9kAsw7vQXgRbZl1LvO+iiUqreQM9cn+ziyA7zV2bPyt82BIBe6dINl1ESFJDAciBriMpDu2LAMKEME0DVi6xODF8xuj2tJEF6EZNPC09kJzTWexMHiWQ7l9C0NRpXf41wxiEbmp4ngCqrc4sth4FIM78C8dBT0DVE6uwfF4P9REIK5T1jODvdiJYzUKlZhrGMGhRTGSbH3uJuWJtHtL5qpR/mmFQBWu+OtNseJ3h6bs5lyP7RABWsCd/rRqh0KpTNsHCK8W12acQeINX3yVNzJt7zKcO0hBPdWZBpcBoeSMl5aWLcplQp6zYjalin96ItDmqRYHas+WibnRXfnZCwVXlLuBAvNbabpBPJ2B8Xb8S61PBqFCZ7nXNGFn3DHW/RlfovUc/qjzOubipB4VnVnRKELgGmB4rayWNeZ2vWsKtfpmSVGrWHpw/FOkEBgsBLzXhVx0drUGavjFm/G+ekiODnMxoXBlWIaxiedG7oJcYE3xz2Do9E39bZq+NQ6PxHS7lsNT2GgoxV1UF3Jdc757pIntFbc6Rp0d6qGCABMp0gkB1IpIT9IwCVLyUs8w5FzkICggAyKSGwUvkYYyoZumZXYHdG6ahlsqMgvW/7J82q0nu1Z+8gc3ca7NMLh5HZQQoEV6/sbUz5wsm8JwwPaAjANevEmRY0dlk2QJHEMmTxGxSw4CtE3DoNPmNpPanusmsnGnJVNa15UCaP5RQjLJxJC3klmyohT1iqXkV5GsCAjMGmVqZuizZswhgdoyLCHawoGLCBWbsoIs6aJD9SUG+E+98usdflJ9DcAYWyB28ffr7bHJXUn0NewDIp0JHuGW8JA4/slvwouAQ9za/AmtlJM1E7Z9/5vjBr+Kl3efFdy1uVqsCDS88Qi1aY3NiR7ar+Is1+S+fELImjP6EsolnVGUchrClUfoxVFlfF6iEsjgfu/8aMIVsmLaDUvZGCbnCDe38GdDHH99ZFfdOk9weh6zeICh4ikFl0K1bqhPnxrLnjresb921wdKKArfuGdaZO947BGt4vhYw3/4TCEe4SZoXdk3asAqEw3FACbipxwxKYZTCz6DbnJXzLalESU8RD3hLEFm88U6kCIk4jl6Ay2QFNdlWQZQGaUO207sxRVnipJMfib2cv6wiDiZmc/gMk04GpaFtfHgKLhuMc7wKYIwv/eqxmZMwZk9KCQE0RbMGMcza1QgnEYxi1bKPGYrcrAqIkH8JMBLu30QdeIcfef9L0ywhDxjl023zv7QR654fNob3TffcM6ql//31qu/uO+PCz8FbdbLb56vv21F/37r3FP/mrlzw7fL4rf8ZK7vB+G2lvaq+J1ChSQ/HPxEACvx2zFbzaPPVr/HpKEaIL6t8rEWjWED4iOj+BTXdf7i0CHHPCvUoL28Q5uHPwiEV2+Df/v0gouf29fkv3ardVm49fiRbdSspZgnTvAXW3SDAS1lkc3/XMYJ1DauaF/kY2zes+eEqxcS64C/0tRjuuUPlBlkx0WorrLNvKG9bjw0UgtES3IKXNfWBeQyRDqxH+55seilz13/83PjDmZYVLNmGpplXMHRVgF6S7xr1kYzvJTyUl5Oimfr1/x40+/2X25W7/4Q1B0hz079zm9av/vtF4+cP737rrKG17pLN721xJgKR+958paTOC6RTPPkeDgROCMmY9FJELqQrOgEfvD161666LWnio796BfLxXdHHr/v2PrH/GbnDL7zf/ZXTP3ZjIUAXQ9cxNqboTHGx2pYazCCJzbgA3JEa8eGhmB11wRj6xxWWx8LnCgrxuJiPkoxARuVYt8Qw4QaBz9qbXkU81b9rF33y0RMrwMd3tqMDuOEGwxHvP7f+39JpqLPi2CnmA7mQhGIAUlqGTRatG0ibGHF0ABj+V9en4F8hNSCgAmh8/Xl3YvLlvvgT9PZrqIXvvLYk8t2h/Ye+3PpWZdBrPubY8jbNQFY3YGFSdq+jcDbv/sklpAvifnJO8El9fA7bLWdDwteEBiwSAvZzuJLjJa6lbAGaAXoU6R8GGBXO91fd2xqxzF4eKrTA/AIUoO4cVwHa2r9DMLxTYjb/KLbCmLSRcc3r8hAC+qxcbseb0djOp0k8tIm4jexIbgQlbY4KSLeT7Jee+7S3rOwBy+jtkRXXPiJKSwVH5603JZ+d9zYNOhaip3AgKhjwI6uR8eBD6EnexOvKdChC1OdvuLI5eIxFKJeQXFdwTZL4Yn01HeS9EgWIv0kt3/0M9soFP8q1hl/5YAvpYiI2juDDgP2sM2ECEMmrxMpusGCUGv3jL4gpyJDOlEsOQrVgu0TZuDVyrB0hvpTiqccoCZpmxBXNHoRwE6jKBsCfY3DbPmGkN8+CLr5IOjoVUWQWOn9ijkZAmWWDoGG23vNrxIRAX15zUSxCIOt4bKUGbz/6DA7yw4IcYhUiCuTzWHSx6bCy87YEjAuFoF8yWlxmk9+v/zoXTJn9Lg/GXFDeB272w0LnxcLa8srcEGK5LG8aaEJLCa5aY5h4U6ORj2yqQJVshIUF3GCEPVQpFWEuK/y6x8eA/DKhp5ZDf7bBaVFQqoXEg0YYEKguWjC/312xuppJt6ASKoWP/2Ji30JU+NziQEcA3sX+3DyafJrpMOo5c+DwX09S7bzo7v3VPf09V8qniREKjgajvYbEahl4s2SVeJn7ci4BNiWagwCf3ufDRmGGQoIouI/PbrNt67n+66CWz8N63Db1eSOsMyR4rDgoeQeEEtJArBEXBc/A2MVUUBrot4DKlPYFuVCxktsoojpR0q9TISGifg8rU4b+NyculROKQc6M1e1VtYmhM/+UsQRdOFAeQc6CGVwwe+K5iD05RJuwYmhE8U/QRri0MKDBtYWw9FaXPDBLys/4eMicaU56Vh16YlTGJwNvFqrowvWYHcDmM6jhARFCOG/tHtqFfbeR0icNuoE7+RB48C2hw/9euV57LGzX+SV649deXmURcwHH//47fgbM4NxvEt8bsLh64zdPpQNMxz/ENOwrSV8zbXaEoBXhUGNBLBaKVQnZRj2jPVpKSliA4isTqDjVWJX18vpEaYUMca/jIStIqhpPhgNcpdDN/REczbccGIcvmk8CosjjFSiaFmQSXHRDcFoXQVP31qDIb4pehcpgt4qbuAeMTH5jN1l2uWYIc5tPcK9NH4kzlZEsceblsPlV5Z89dg2P42wBthK4P5DojwI8MlElLHS7s/iV43ahvNXyDQnY64eE4LoUKxG1WQM73wDq63zizCoEb2tmJdqRttKUtm488/8pVs+/Y/W3+MmSinw2xmYFRG/TkI/3P4E6Csn7TgAgZZZjKJh15bB7rr6bwaKLoCrF+nGdNSFhAAy/pAO1eMftDfisKfs3X3fGFE8wG7cdqmWgEtHsPpBZ35dB7xESeJ+iOj45rNcs8uzIV4JNQJSbFsmhitfT5gGbx4KtBKt7urnoG7D0z+MvdM94WCJjzay+snP+54M4QYch/hasPYQHDFe8mOEQT4V8WqR4ZizgZEsQJf9y7CnzlY3A3UDPX3usPCtWqzWk9xLf2n+nERzHLXFUZJr5ituBrvoFp3HN+s+0iZk6AJwZIn3C3IC0nSytQSOTP9CDXRf5XSOdKEc4vqZvQtRNBpYrWHcURTE39jqhMsWCeLuNpqFna8JpnwQ9N6VyFTzi5//jEesdPwfXwK+tkL/yC2v22zr3jKcHLFinR+Dw9DViLOmTV3EBOeBRuyWNnVevw57Ri3E6hyG40lcNC7evSeDvB1KV3f8OGryOdHlM8HHjbgWOluPItiY4/oJ6DC0/l+Rpi6KfaJ5Biy3ApoO53z4phtPPeaLw9pKuU33G6v2jD2zAXuKeBvYUsyG6oOrq4LQCB1fEJHvXB8XXiSYQEMagJI9iSNwpEbw6YUQcTYpsD44aLbeBl8LCBRyIpNoLINgc7LLJDX5UJD2FGZ4ZlAKyQxpEsJUefIrTrXaGttmz70YW8gRl0ujTlgVuvWVtGzYa4DSYnQlHLJurghzAqg5O2GjRPBqaZtv6J9qM4q6IESBRv5xG+7T0uw5Cy0l58bMw/CJX5rIyfthp1HHaqZVNG81pzCqu1ueUVz1BXBJBLxKQK0FPqoz7Nq4jmE376g8WHy/3TaYtLEG7wK+4eOf/R6Y++7S9cbF71x6we5A0Lx2RTV0mNVlF+oHt+/5wtQilP0VlE8vuVS0r9Oool/lRkwv18lq7qtbLkaKILYQqnAxBaRhcoAExp5FtLFl7306pbfYgqkuVkISx732WXctkis7m3FHHS7YmQzbDjUuMXwhMJd4eTLMcQyvkqE6YY3RgstC9MpgwgU+nN92f+xn4Zbi9WeY+Dv32EOMSUlMR1+EaxlO7t4ezJEpiYvB4cxXGArZXI/LUs/QOCaJP5s60kYi3qHkTRFso9DyZPad8MG//P6uclwJ63jFeEencCN+saHIxzRz2745B2poLZxY2fn6429z3mQsfMvvW/TOebdM/OyB199n/vk/3rzv1TdPvn8OP/DAA1dHijQ4YzEJc7h3S5Aw0HYFKkkr9i1sGBOqWoM339m9+JYpFQ1X40J58Zw6bRXjPEaAHjbJGhJeB+Z4KMFW2wjs46uj95p3tPjZC/SV/zx5xV+gbOHkmCa7RzlqO4IzNCVbV+kWEDzog7UtNfNxvowG4No7b5u5seH5q2Zvaj/+BCHPfOvAos03Lnp07TLaefBlYUYLA5gC1rzz/lAyucLuE7wYb25al22HaTVdEmdfA1xgEALi6PjurgPk3quMrTHaYJ9U8zNZtKu8vhzvmyqJwQjeu1uMzu38acXPX1yqb3jofUtOjnlmKTYmR4iNcEsJp/pZ8Mrfjp+qoWT3HDC6JgtAlmrv0YMAn1qy1NTxseRg9/3Hjsquw4G04lx6p1mG/chudi4vgBDXNFSJeWHuSmbE6ps1fd/JBb84E/5lhCtuuIevxfWedfa8/fuf6l7zxPGfPPW3t35/5Z+Kwg2Yy0RjaLW1OhYYI7uO7+6nEz0K53IKY6ALaowg3FEpCsA3A/mEf24VLmzkq5ibnmllZ31XHHKl0jpRFXzSCMaCjl1f53U+/fyEiDGZiltpjWsURRjyCdyG70I/HHzPTq0IGOEQjeEd5fRKbT7AGSgMwLeH91dSfuB9zCy5seamfz76q+4nTi4wv/3UOIi+bJS//0OX4mkY0ixGHt+m0yp45qrXzBLmu7e9qvwwbqUHfVwkSxKTCFYcj2Ij5zD+1zlkZ8f3WQlt5WM3Bm58mjUDrftW/YnZ5z7rtw5vgSevnPD2x7esOP6C3nXOmBpuvrCJPfvwm6Z54fP4XuqX1+6+Hd4YG6167Wv7KAIakorhJevQWM3AvhDDuAbBCqwhUhMXU4IlgvitXK1yT6U7twlWZlpAQrjQ3qHFJnGYwtNlIshoKjbT2d544hY8uxSdo1HaJk305kyE44lQpkBLG1jimwI6E6ldG+sdIcq0Pb+Y2yhj/joq/OiaCMdJDtfxgmxX9KhyiP8//xMcIA==; expires=Wed, 09-Jun-2021 10:18:14 GMT; domain=forum.dlang.org; path=/

Although I do not think it is linked to the page I was trying to view it happened while following the link in this post http://forum.dlang.org/post/axbqxsgaknqawhghtpie@forum.dlang.org

**Comment by CyberShadow** [comment]
OK, I see now you were visiting the forum via HTTPS, which goes through Apache.

**Comment by CyberShadow** [comment]
Or were you? http:// URLs should've went through nginx, no Apache in-between

**Comment by CyberShadow** [comment]
Can you still reproduce the problem? If so, can you try http:// vs. https:// ?
