### ISSUE TITLE
Add "display threads only" option to advanced search

### ISSUE THREAD

**Issue by AndrejMitrovic** [CyberShadow/DFeed#75]
When using advanced search for example to find threads by their subject (http://forum.dlang.org/search?q=&advsearch=Advanced+search) there is no way to list only threads. Instead all the posts for the very first matching thread are listed, followed by the second thread's posts, and so on..

It makes it very difficult to find a thread since an average one has hundreds of posts.

**Comment by CyberShadow** [comment]
For now you can use `newthread:y` in the query.

**Comment by AndrejMitrovic** [comment]
Ooh what a cool little gem! :) Thanks.

**Comment by wilzbach** [comment]
> Ooh what a cool little gem! :) Thanks.

@CyberShadow maybe you can find a prominent place to link / document such nice features? You already invested so much time into DFeed, don't misrepresent your efforts -  show your features!

**Comment by CyberShadow** [comment]
Or I can add a checkbox. When I get around to it.

**Comment by CyberShadow** [comment]
> @CyberShadow maybe you can find a prominent place to link / document such nice features?

BTW, that place is [the help page](http://forum.dlang.org/help). This one is really just a case of me forgetting to add a checkbox, though.

**Comment by CyberShadow** [comment]
Has it really been that long?

Added the checkbox in 6759234bb66bdd2ba10c9a25b1601c6b0e23f4e6.
