### ISSUE TITLE
Some way to disable the keyboard shortcuts

### ISSUE THREAD

**Issue by Wyatts** [CyberShadow/DFeed#8]
I'd appreciate some way to disable the keyboard shortcuts. They interfere with find-as-you-type in my browser and, even when I'm not searching, I end up accidentally losing my place more often than I find myself benefiting from them.

UI-wise, I'm thinking a checkbox above or below the pane that describes the shortcuts.  Also, a cookie to store the value would be welcome if it's not too much trouble.

**Comment by CyberShadow** [comment]
This is now implemented.

http://beta.forum.dlang.org/

**Comment by Wyatts** [comment]
Awesome, thanks for this (and the other two)!
