### ISSUE TITLE
posting doesn't work

### ISSUE THREAD

**Issue by d-random-contributor** [CyberShadow/DFeed#80]
Shows "connecting to server" and no progress after that.

**Comment by CyberShadow** [comment]
This post made from the forum 4 minutes ago seems to indicate otherwise?

http://forum.dlang.org/post/tvgqobyjtmvlylkqvxdm@forum.dlang.org

**Comment by d-random-contributor** [comment]
So it doesn't work only for me? Today I posted [here](https://forum.dlang.org/post/hdiifmdfctuiigxpchug@forum.dlang.org) and yesterday [here](https://forum.dlang.org/post/temkficskxstlsfnevbp@forum.dlang.org).

**Comment by d-random-contributor** [comment]
Waiting now for connection.

**Comment by CyberShadow** [comment]
Yeah, I see now that the connection to the NNTP server is timing out.

Will forward "upstream".

**Comment by CyberShadow** [comment]
I've been told this should now be resolved.
