### ISSUE TITLE
Message not appearing on forum.dlang.org

### ISSUE THREAD

**Issue by s-ludwig** [CyberShadow/DFeed#87]
I just re-posted a vibe.d version announcement using the web frontend, after it didn't show up there after I used Thunderbird. Now I'm sitting endlessly at http://forum.dlang.org/posting/mmfrsonxrfxwltkfvliw - seems like there is something about the message that somehow confuses DFeed?

**Comment by wilzbach** [comment]
Pretty weird, but nothing is appearing on the web interface, so maybe the Spam protection is blocking you? In this case, maybe simply a different IP will do the trick?

**Comment by s-ludwig** [comment]
Hm, shouldn't it display a captcha in that case? I can try to re-post with another IP later. Just tried with different contents and still nothing appears on the forum.

**Comment by wilzbach** [comment]
> shouldn't it display a captcha in that case?

Yeah, maybe it's also related to the migration of the forum to btrfs, but I guess only @CyberShadow really knows what's going on.

**Comment by s-ludwig** [comment]
Posting from a different IP didn't work for me either. At the same time, Martin was able to post the 2.075.0-b4 announcement...

**Comment by wilzbach** [comment]
>  At the same time, Martin was able to post the 2.075.0-b4 announcement...

Wow I am not seeing that one either:

![screenshot_2017-07-10-17-49-35-178_com android chrome](https://user-images.githubusercontent.com/4370550/28027144-633135a4-6598-11e7-8323-2296bccb12bb.png)

**Comment by s-ludwig** [comment]
You are right. I wasn't looking carefully and mistook the b2 one for it, because it's in the same spot.

**Comment by wilzbach** [comment]
> You are right. I wasn't looking carefully and mistook the b2 one for it, because it's in the same spot.

Well, if you want to post it today, you could send me your text & I can try whether I have more luck. I never had problems so far.

**Comment by s-ludwig** [comment]
Never had problems either. But since Martin didn't get through either, I'd assume that something is simply broken. Bad timing, but now the message is already out.

**Comment by aG0aep6G** [comment]
forum.dlang.org seems to have a major hickup. The newest post it shows is 7 hours old, but there's been plenty activity since then.

**Comment by CyberShadow** [comment]
Thanks all, I gave it a kick and it seems to be syncing now. I will be investigating why it got stuck, but it's probably somehow related to the filesystem migration we're doing on the server.

**Comment by CyberShadow** [comment]
Well, I won't be getting any answers from the log files this time :/ They just cut off past 2 AM UTC.

I'll try to grab a stack trace before restarting it should it happen again.

**Comment by joakim-noah** [comment]
I can't post right now, gets stuck in a loop when saying, "Message sent.  Waiting for announcement."
