### ISSUE TITLE
Font size in DForum reply mode changes based on window size

### ISSUE THREAD

**Issue by ghost** [CyberShadow/DFeed#9]
The reply mode seems to change the font size based on the window size, here's some examples:

http://i.imgur.com/srLZESm.png
http://i.imgur.com/ubrn5ji.png
http://i.imgur.com/SwadBtx.png

It should rather wrap text around like the rest of the website does.

Using Firefox and Chrome recreate this behavior.

**Comment by CyberShadow** [comment]
Fixed in `next` branch
