### ISSUE TITLE
Draft: error accessing May 02 draft, can't dismiss banner

### ISSUE THREAD

**Issue by SimonN** [CyberShadow/DFeed#90]
My Dlang forum account is SimonN.

When I click "reply" on any post or click "create thread", I land on the page with the normal text input boxes, and at the top a yellow banner: "You have an unsent draft message from May 02."

The banner links to "http://forum.dlang.org/posting/xgwdtmcwvydwdwjefvze". I click on that address, I land on an error page: "Expected n, got {".

This doesn't discard the draft.

**Expected instead:** No error. Some way to discard the draft, dismissing the yellow banner for this particular draft. (The draft is so old that I don't remember or want it anymore.)

**Comment by CyberShadow** [comment]
Thanks for the report. Should be fixed now.

**Comment by SimonN** [comment]
That was quick, thanks!

The banner was in place as before, but loaded the correct draft as expected, which I could then discard.
