### ISSUE TITLE
Redirect to HTTPS by default

### ISSUE THREAD

**Issue by wilzbach** [CyberShadow/DFeed#95]
Chrome Dev starts to complain for non-SSL sites:

![image](https://user-images.githubusercontent.com/4370550/35446634-9de62488-02b5-11e8-9481-519298b4855c.png)

Google also downrates you for not doing so by default, see e.g.

- https://www.searchenginejournal.com/google-is-requiring-https-for-secure-data-in-chrome/183756/
- https://motherboard.vice.com/en_us/article/xygdxq/google-will-soon-shame-all-websites-that-are-unencrypted-chrome-https

**Comment by CyberShadow** [comment]
Thanks for the reminder, it's past time.

Fixed: https://github.com/cybershadow/DFeed/compare/d07d2b71b05c907c292fb3d09e02f78a65d020d7...264ca8aa07a07ec4ceddd149a94a44a6117f0af7
